### ISSUE TITLE
Items in localStorage are not being namespaced

### ISSUE THREAD

**Issue by antoniomercado** [thinknode/desktop#12]
### Acceptance Criteria

An interface to localStorage is necessary because of two facts:

1. In the Desktop, you can maintain logins for many different accounts.
2. The Desktop client "remembers" ids and other things based upon a user's action.

This is a problem because if someone enters a valid context under their login A for account X this will not be valid for the same user under their login B for account Y. In the case of calculation, entry, or object ids, it wouldn't even make sense for the ids to be shared across logins in within the same account. To solve this, we introduced namespacing, which has been partially implemented, but not in a robust modular way.

The solution for this is to make an Angular service/factory/provider that interfaces with localStorage. It is important to note that this is not merely a wrapper. This things must:

* be able to "register" a namespace upon logging in for the first time
* keep a localStorage item that records a list of keys for a given namespace (when a user logs out that namespace and all the keys that live under it should be deleted)
* allow modules to get and set items under their namespace

To be clear, the namespace key must contain the API endpoint, account domain name, and username for the logged in user.

**Illustration**

Key | Value
------------ | -------------
namespaces | {"https://thinknode.io>mydomain>myuser":["key1","key2"],"https://thinknode.io>other>otheruser":["key1","key2"]}
https://thinknode.io>mydomain>myuser>key1 | value1
https://thinknode.io>mydomain>myuser>key2 | value2
https://thinknode.io>other>otheruser>key1 | value1
https://thinknode.io>other>otheruser>key2 | value2

**Comment by kyleburnett** [comment]
Handled in #34
