### ISSUE TITLE
The client reports Failure: when requesting the STATS log type

### ISSUE THREAD

**Issue by kyleburnett** [thinknode/desktop#24]
When performing a GET request on the Logs route in the client with the STATS type, the client returns "Failure:" in red. Manually performing the same route in another REST client (e.g. Postman) works.

**Comment by danielpatenaude** [comment]
*bump*

**Comment by kyleburnett** [comment]
This should be fixed in the [new version](https://github.com/thinknode/desktop/releases/tag/1.3.0). @danielpatenaude can you confirm?

**Comment by danielpatenaude** [comment]
It works, thanks!
