### ISSUE TITLE
POST /calc/:id route UI is missing the route parameter

### ISSUE THREAD

**Issue by tmadden** [thinknode/desktop#32]
There's no way to provide the ID for the calc I want to post.

**Comment by tmadden** [comment]
Oh, and the body text box can also be removed. (Kyle confirmed that it has no purpose.)

**Comment by kyleburnett** [comment]
We just pushed out a documentation release, which might fix your problem with the missing id parameter. I can keep this open to address the request body issue. Simply not using it right now is a valid work-around.
