### ISSUE TITLE
RKS PUT lock and unlock missing ID field

### ISSUE THREAD

**Issue by danielpatenaude** [thinknode/desktop#49]
The URL path has the ID field, but the page for these routes is missing the ID field. I have to change the ID field on the GET route, then come back to the PUT routes.

**Comment by kyleburnett** [comment]
It's missing from the documentation for those routes, so I'll just need to fix that and release the documentation. Won't require a new desktop release, but it will require a new Thinknode release.

**Comment by danielpatenaude** [comment]
No rush. There's a round about way to get past it for now.

**Comment by kyleburnett** [comment]
@danielpatenaude : This issue is now fixed. You might have to close and reopen the app in order for the new route specification to be pulled down.
