### ISSUE TITLE
Calc visualizer doesn't expand nodes that should be expandable

### ISSUE THREAD

**Issue by tmadden** [thinknode/desktop#50]
I've gotten this behavior consistently with this calculation: 57e9806101005f35bc2fd3aac6509b24
with this context ID: 57d1a5f00040e92ade214e2c16733409
on the MGH account.

It highlights the node, but the sidebar doesn't come up, and the node doesn't expand.

Zoltan also saw this behavior with one of his own calculations.

**Comment by kyleburnett** [comment]
I can't seem to reproduce your issue. Are you on the latest version (1.4.1)? Do you know that you have to use the ALT key to expand the node? Another thing: if you have the search window open, the sidebar won't come up. Does it only happen with particular children?

**Comment by tmadden** [comment]
I tried it again, and I was able to get the sidebar to come up, but the nodes still won't expand. (I'm pretty sure I didn't have the search bar up before, but I can't reproduce that behavior again now.) I think both Zoltan and I are running the latest version, but I'm not sure how to check. Where can I see the version number?

**Comment by kyleburnett** [comment]
You can't see the version number in the Desktop app, but the installer should have the version number in the filename. You can just go to https://desktop.thinknode.com/ and download the most recent version.

**Comment by tmadden** [comment]
OK, I'm definitely running the latest version now, and I'm seeing the same behavior as in that last comment. I'm able to drill down into calculations by copying IDs from the sidebar into the top left box, but I can't expand more than one level at a time. This is true even for very small trees. Has anyone been able to use this on Windows successfully?

**Comment by kyleburnett** [comment]
Yes, Daniel was able to use it on your calculation just fine.

**Comment by kyleburnett** [comment]
Try closing the app completely and reopening the app. If that doesn't work, can you try cloning the repo and running the app with `grunt start` (you'll have to run `npm install` and `bower install`)?

**Comment by kyleburnett** [comment]
Running the app with grunt start from source will run it in development mode, allowing you to see the developer console. There might be an uncaught error there.

**Comment by tmadden** [comment]
I'm getting this error before anything really happens:

index.html:11 GET file:///C:/thinknode/desktop/assets/css/styles.css net::ERR_FILE_NOT_FOUND

The whole app is unstyled and the canvas doesn't seem to be behaving properly, so it's hard to evaluate anything beyond that.

**Comment by tmadden** [comment]
Oh, something in the command window is complaining about Ruby and Sass missing. Are those required too?

**Comment by kyleburnett** [comment]
Sorry, yes those are required. Ruby should come with `gem`. Once you have ruby installed, you should do `gem install sass`.

**Comment by tmadden** [comment]
OK, thanks. I got that installed and the app looks normal now. I get this error in the console right as the app is starting.

C:\thinknode\desktop\node_modules\d3\node_modules\d3-hierarchy\build\d3-hierarchy.js:861 Uncaught TypeError: Cannot read property 'children' of undefined

**Comment by kyleburnett** [comment]
Closing as this was resolved by using the ALT key as mentioned above.
