### ISSUE TITLE
As a user, I'd like to browse RKS entries from the desktop client

### ISSUE THREAD

**Issue by antoniomercado** [thinknode/desktop#8]
[RKS Visualizer.pdf](https://github.com/thinknode/desktop/files/338048/RKS.Visualizer.pdf)

**Comment by antoniomercado** [comment]
*Acceptance Criteria*

The only things that should be implemented in this ticket are what is described below. Anything additional should be saved for future tickets or cleared with Sal or Kyle first.

_*ui*_
This should behave just like the nested finder view in OSX. See the attached document for the UI specification. The only thing not pictured that needs to be included is a selection mechanism for the bucket or context to use when querying.

_*code*_
Care should be taken to ensure that queries are performed efficiently (and only when needed) and the results are stored in an extensible way (since filtering options might be added in the future).

**Comment by soxsnation** [comment]
Can you add the ability to delete an rks record (probably should prompt user before actually deleting as well)

**Comment by danielpatenaude** [comment]
Having a scroll bar in a scroll bar for the right side pane is a little painful. For example:

Context: 57b309920040cedd8ea4619f9e01a960
record: 006-17-15cd
 Follow the RKS path all the way to the treatment_plan (39db6d4f-21d6-4e15-bac0-de6570c9d39b). It's very difficult to scroll through the editor when you have to manipulate two scroll bars at the same time everytime you scroll to the end of one.
